### ISSUE TITLE
env var YAML cleanup for CA-VICTORIA-K8S-T2

### ISSUE THREAD

**Issue by rptaylor** [PanDAWMS/harvester_configurations#49]
as indicated here https://github.com/HSF/harvester/issues/144#issuecomment-1226933791
We should be able to remove the env vars from the job YAML, since they are defined by harvester instead: https://github.com/HSF/harvester/blob/master/pandaharvester/harvestermisc/k8s_utils.py#L188

BTW I can't seem to assign this to myself.

**Comment by rptaylor** [comment]
env of a job before cleanup:
```
    env:
    - name: computingSite
      value: $computingSite
    - name: pandaQueueName
      value: $pandaQueueName
    - name: proxySecretPath
      value: $proxySecretPath
    - name: proxyContent
      value: $proxyContent
    - name: workerID
      value: $workerID
    - name: logs_frontend_w
      value: $logs_frontend_w
    - name: logs_frontend_r
      value: $logs_frontend_r
    - name: resourceType
      value: $resourceType
    - name: HARVESTER_WORKER_ID
      value: $HARVESTER_WORKER_ID
    - name: HARVESTER_ID
      value: $HARVESTER_ID
    - name: PANDA_JSID
      value: $PANDA_JSID
    - name: TMPDIR
      value: /pilotdir
    - name: HOME
      value: /pilotdir
    - name: PILOT_NOKILL
      value: "True"
    - name: computingSite
      value: CA-VICTORIA-K8S-T2
    - name: pandaQueueName
      value: CA-VICTORIA-K8S-T2
    - name: resourceType
      value: MCORE
    - name: prodSourceLabel
      value: managed
    - name: pilotType
      value: PR
    - name: pilotUrlOpt
    - name: pythonOption
      value: --pythonversion 3
    - name: pilotVersion
      value: "3"
    - name: jobType
      value: managed
    - name: proxySecretPath
      value: /proxy/x509up_u25606_prod
    - name: workerID
      value: "16869968"
    - name: logs_frontend_w
      value: https://aipanda047.cern.ch:25443/server/panda
    - name: logs_frontend_r
      value: https://aipanda047.cern.ch:25443/cache
    - name: stdout_name
    - name: PANDA_JSID
      value: harvester-CERN_central_k8s
    - name: HARVESTER_WORKER_ID
      value: "16869968"
    - name: HARVESTER_ID
      value: CERN_central_k8s
    - name: submit_mode
      value: PULL
    - name: EXEC_DIR
      value: /scratch/executables
    - name: TMPDIR
      value: /pilotdir
    - name: HOME
      value: /pilotdir
    - name: PANDA_HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: K8S_JOB_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
```
