### ISSUE TITLE
remove k8s command and args for python3 after migration to EL9

### ISSUE THREAD

**Issue by rptaylor** [PanDAWMS/harvester_configurations#73]
We set 
```
containers:
  - args:
    - -c
    - cd; python3 $EXEC_DIR/pilots_starter.py || true
    command:
    - /usr/bin/bash
```
to facilitate migrating to python3 and EL9, but after all queues are migrated this should be changed at the Harvester default level, then the args and command should be unset in job templates again.  @fbarreir
